// flow-typed signature: ba633019eb92048928eb36d2acd4577d
// flow-typed version: <<STUB>>/babel-plugin-ignite-ignore-reactotron_v^0.3.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-ignite-ignore-reactotron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-ignite-ignore-reactotron' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-ignite-ignore-reactotron/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-ignite-ignore-reactotron/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-ignite-ignore-reactotron/lib/index'>;
}
