// flow-typed signature: f3e431cc481b94dbea95f04f0e61bd12
// flow-typed version: <<STUB>>/ignite-dev-screens_v^2.3.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ignite-dev-screens'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ignite-dev-screens' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ignite-dev-screens/plugin' {
  declare module.exports: any;
}

declare module 'ignite-dev-screens/templates/APITestingScreen' {
  declare module.exports: any;
}

declare module 'ignite-dev-screens/templates/ButtonBox' {
  declare module.exports: any;
}

declare module 'ignite-dev-screens/templates/ComponentExamplesScreen' {
  declare module.exports: any;
}

declare module 'ignite-dev-screens/templates/DeviceInfoScreen' {
  declare module.exports: any;
}

declare module 'ignite-dev-screens/templates/DevscreensButton' {
  declare module.exports: any;
}

declare module 'ignite-dev-screens/templates/DevTheme/ApplicationStyles' {
  declare module.exports: any;
}

declare module 'ignite-dev-screens/templates/DevTheme/Colors' {
  declare module.exports: any;
}

declare module 'ignite-dev-screens/templates/DevTheme/Fonts' {
  declare module.exports: any;
}

declare module 'ignite-dev-screens/templates/DevTheme/Images' {
  declare module.exports: any;
}

declare module 'ignite-dev-screens/templates/DevTheme/index' {
  declare module.exports: any;
}

declare module 'ignite-dev-screens/templates/DevTheme/Metrics' {
  declare module.exports: any;
}

declare module 'ignite-dev-screens/templates/FaqScreen' {
  declare module.exports: any;
}

declare module 'ignite-dev-screens/templates/PluginExamplesScreen' {
  declare module.exports: any;
}

declare module 'ignite-dev-screens/templates/PresentationScreen' {
  declare module.exports: any;
}

declare module 'ignite-dev-screens/templates/Styles/APITestingScreenStyles' {
  declare module.exports: any;
}

declare module 'ignite-dev-screens/templates/Styles/ButtonBoxStyles' {
  declare module.exports: any;
}

declare module 'ignite-dev-screens/templates/Styles/ComponentExamplesScreenStyles' {
  declare module.exports: any;
}

declare module 'ignite-dev-screens/templates/Styles/DeviceInfoScreenStyles' {
  declare module.exports: any;
}

declare module 'ignite-dev-screens/templates/Styles/DevscreensButtonStyles' {
  declare module.exports: any;
}

declare module 'ignite-dev-screens/templates/Styles/FaqScreenStyles' {
  declare module.exports: any;
}

declare module 'ignite-dev-screens/templates/Styles/PluginExamplesScreenStyles' {
  declare module.exports: any;
}

declare module 'ignite-dev-screens/templates/Styles/PresentationScreenStyles' {
  declare module.exports: any;
}

declare module 'ignite-dev-screens/templates/Styles/ThemeScreenStyles' {
  declare module.exports: any;
}

declare module 'ignite-dev-screens/templates/ThemeScreen' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ignite-dev-screens/plugin.js' {
  declare module.exports: $Exports<'ignite-dev-screens/plugin'>;
}
declare module 'ignite-dev-screens/templates/APITestingScreen.js' {
  declare module.exports: $Exports<'ignite-dev-screens/templates/APITestingScreen'>;
}
declare module 'ignite-dev-screens/templates/ButtonBox.js' {
  declare module.exports: $Exports<'ignite-dev-screens/templates/ButtonBox'>;
}
declare module 'ignite-dev-screens/templates/ComponentExamplesScreen.js' {
  declare module.exports: $Exports<'ignite-dev-screens/templates/ComponentExamplesScreen'>;
}
declare module 'ignite-dev-screens/templates/DeviceInfoScreen.js' {
  declare module.exports: $Exports<'ignite-dev-screens/templates/DeviceInfoScreen'>;
}
declare module 'ignite-dev-screens/templates/DevscreensButton.js' {
  declare module.exports: $Exports<'ignite-dev-screens/templates/DevscreensButton'>;
}
declare module 'ignite-dev-screens/templates/DevTheme/ApplicationStyles.js' {
  declare module.exports: $Exports<'ignite-dev-screens/templates/DevTheme/ApplicationStyles'>;
}
declare module 'ignite-dev-screens/templates/DevTheme/Colors.js' {
  declare module.exports: $Exports<'ignite-dev-screens/templates/DevTheme/Colors'>;
}
declare module 'ignite-dev-screens/templates/DevTheme/Fonts.js' {
  declare module.exports: $Exports<'ignite-dev-screens/templates/DevTheme/Fonts'>;
}
declare module 'ignite-dev-screens/templates/DevTheme/Images.js' {
  declare module.exports: $Exports<'ignite-dev-screens/templates/DevTheme/Images'>;
}
declare module 'ignite-dev-screens/templates/DevTheme/index.js' {
  declare module.exports: $Exports<'ignite-dev-screens/templates/DevTheme/index'>;
}
declare module 'ignite-dev-screens/templates/DevTheme/Metrics.js' {
  declare module.exports: $Exports<'ignite-dev-screens/templates/DevTheme/Metrics'>;
}
declare module 'ignite-dev-screens/templates/FaqScreen.js' {
  declare module.exports: $Exports<'ignite-dev-screens/templates/FaqScreen'>;
}
declare module 'ignite-dev-screens/templates/PluginExamplesScreen.js' {
  declare module.exports: $Exports<'ignite-dev-screens/templates/PluginExamplesScreen'>;
}
declare module 'ignite-dev-screens/templates/PresentationScreen.js' {
  declare module.exports: $Exports<'ignite-dev-screens/templates/PresentationScreen'>;
}
declare module 'ignite-dev-screens/templates/Styles/APITestingScreenStyles.js' {
  declare module.exports: $Exports<'ignite-dev-screens/templates/Styles/APITestingScreenStyles'>;
}
declare module 'ignite-dev-screens/templates/Styles/ButtonBoxStyles.js' {
  declare module.exports: $Exports<'ignite-dev-screens/templates/Styles/ButtonBoxStyles'>;
}
declare module 'ignite-dev-screens/templates/Styles/ComponentExamplesScreenStyles.js' {
  declare module.exports: $Exports<'ignite-dev-screens/templates/Styles/ComponentExamplesScreenStyles'>;
}
declare module 'ignite-dev-screens/templates/Styles/DeviceInfoScreenStyles.js' {
  declare module.exports: $Exports<'ignite-dev-screens/templates/Styles/DeviceInfoScreenStyles'>;
}
declare module 'ignite-dev-screens/templates/Styles/DevscreensButtonStyles.js' {
  declare module.exports: $Exports<'ignite-dev-screens/templates/Styles/DevscreensButtonStyles'>;
}
declare module 'ignite-dev-screens/templates/Styles/FaqScreenStyles.js' {
  declare module.exports: $Exports<'ignite-dev-screens/templates/Styles/FaqScreenStyles'>;
}
declare module 'ignite-dev-screens/templates/Styles/PluginExamplesScreenStyles.js' {
  declare module.exports: $Exports<'ignite-dev-screens/templates/Styles/PluginExamplesScreenStyles'>;
}
declare module 'ignite-dev-screens/templates/Styles/PresentationScreenStyles.js' {
  declare module.exports: $Exports<'ignite-dev-screens/templates/Styles/PresentationScreenStyles'>;
}
declare module 'ignite-dev-screens/templates/Styles/ThemeScreenStyles.js' {
  declare module.exports: $Exports<'ignite-dev-screens/templates/Styles/ThemeScreenStyles'>;
}
declare module 'ignite-dev-screens/templates/ThemeScreen.js' {
  declare module.exports: $Exports<'ignite-dev-screens/templates/ThemeScreen'>;
}
