// flow-typed signature: 2bbc246c7d97cacb69637bb97f38531a
// flow-typed version: <<STUB>>/ignite-ir-boilerplate_v^2.3.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ignite-ir-boilerplate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ignite-ir-boilerplate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ignite-ir-boilerplate/boilerplate' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Components/AlertMessage' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Components/AlertMessage.story' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Components/DrawerButton' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Components/DrawerButton.story' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Components/FullButton' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Components/FullButton.story' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Components/RoundedButton' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Components/RoundedButton.story' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Components/Stories' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Components/Styles/AlertMessageStyles' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Components/Styles/DrawerButtonStyles' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Components/Styles/FullButtonStyles' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Components/Styles/RoundedButtonStyles' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Config/AppConfig' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Config/DebugConfig' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Config/index' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Config/ReactotronConfig' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Containers/App' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Containers/LaunchScreen' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Containers/RootContainer' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Containers/Styles/LaunchScreenStyles' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Containers/Styles/RootContainerStyles' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Navigation/AppNavigation' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Navigation/ReduxNavigation' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Navigation/Styles/NavigationStyles' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Redux/CreateStore' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Redux/GithubRedux' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Redux/index' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Redux/NavigationRedux' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Redux/ScreenTrackingMiddleware' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Redux/SearchRedux' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Redux/StartupRedux' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Sagas/GithubSagas' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Sagas/index' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Sagas/StartupSagas' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Services/Api' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Services/ExamplesRegistry' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Services/FixtureApi' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Themes/ApplicationStyles' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Themes/Colors' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Themes/Fonts' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Themes/Images' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Themes/index' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Themes/Metrics' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/App/Transforms/ConvertFromKelvin' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/storybook/addons' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/storybook/index' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/Tests/Components/AlertMessageTest' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/Tests/Components/DrawerButtonTest' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/Tests/Components/FullButtonTest' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/Tests/Components/RoundedButtonTest' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/Tests/Redux/GithubReduxTest' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/Tests/Sagas/GithubSagaTest' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/Tests/Sagas/StartupSagaTest' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/Tests/Services/FixtureAPITest' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/boilerplate/Tests/StoriesTest' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/commands/component' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/commands/container' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/commands/list' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/commands/listview' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/commands/redux' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/commands/saga' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/commands/screen' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/lib/patterns' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/lib/react-native-version' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/options' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/plugin' {
  declare module.exports: any;
}

declare module 'ignite-ir-boilerplate/screenExamples' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ignite-ir-boilerplate/boilerplate.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Components/AlertMessage.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Components/AlertMessage'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Components/AlertMessage.story.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Components/AlertMessage.story'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Components/DrawerButton.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Components/DrawerButton'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Components/DrawerButton.story.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Components/DrawerButton.story'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Components/FullButton.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Components/FullButton'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Components/FullButton.story.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Components/FullButton.story'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Components/RoundedButton.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Components/RoundedButton'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Components/RoundedButton.story.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Components/RoundedButton.story'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Components/Stories.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Components/Stories'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Components/Styles/AlertMessageStyles.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Components/Styles/AlertMessageStyles'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Components/Styles/DrawerButtonStyles.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Components/Styles/DrawerButtonStyles'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Components/Styles/FullButtonStyles.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Components/Styles/FullButtonStyles'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Components/Styles/RoundedButtonStyles.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Components/Styles/RoundedButtonStyles'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Config/AppConfig.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Config/AppConfig'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Config/DebugConfig.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Config/DebugConfig'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Config/index.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Config/index'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Config/ReactotronConfig.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Config/ReactotronConfig'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Containers/App.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Containers/App'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Containers/LaunchScreen.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Containers/LaunchScreen'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Containers/RootContainer.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Containers/RootContainer'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Containers/Styles/LaunchScreenStyles.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Containers/Styles/LaunchScreenStyles'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Containers/Styles/RootContainerStyles.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Containers/Styles/RootContainerStyles'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Navigation/AppNavigation.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Navigation/AppNavigation'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Navigation/ReduxNavigation.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Navigation/ReduxNavigation'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Navigation/Styles/NavigationStyles.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Navigation/Styles/NavigationStyles'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Redux/CreateStore.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Redux/CreateStore'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Redux/GithubRedux.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Redux/GithubRedux'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Redux/index.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Redux/index'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Redux/NavigationRedux.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Redux/NavigationRedux'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Redux/ScreenTrackingMiddleware.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Redux/ScreenTrackingMiddleware'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Redux/SearchRedux.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Redux/SearchRedux'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Redux/StartupRedux.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Redux/StartupRedux'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Sagas/GithubSagas.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Sagas/GithubSagas'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Sagas/index.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Sagas/index'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Sagas/StartupSagas.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Sagas/StartupSagas'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Services/Api.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Services/Api'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Services/ExamplesRegistry.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Services/ExamplesRegistry'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Services/FixtureApi.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Services/FixtureApi'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Themes/ApplicationStyles.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Themes/ApplicationStyles'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Themes/Colors.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Themes/Colors'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Themes/Fonts.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Themes/Fonts'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Themes/Images.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Themes/Images'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Themes/index.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Themes/index'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Themes/Metrics.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Themes/Metrics'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/App/Transforms/ConvertFromKelvin.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/App/Transforms/ConvertFromKelvin'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/storybook/addons.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/storybook/addons'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/storybook/index.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/storybook/index'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/Tests/Components/AlertMessageTest.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/Tests/Components/AlertMessageTest'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/Tests/Components/DrawerButtonTest.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/Tests/Components/DrawerButtonTest'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/Tests/Components/FullButtonTest.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/Tests/Components/FullButtonTest'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/Tests/Components/RoundedButtonTest.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/Tests/Components/RoundedButtonTest'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/Tests/Redux/GithubReduxTest.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/Tests/Redux/GithubReduxTest'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/Tests/Sagas/GithubSagaTest.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/Tests/Sagas/GithubSagaTest'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/Tests/Sagas/StartupSagaTest.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/Tests/Sagas/StartupSagaTest'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/Tests/Services/FixtureAPITest.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/Tests/Services/FixtureAPITest'>;
}
declare module 'ignite-ir-boilerplate/boilerplate/Tests/StoriesTest.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/boilerplate/Tests/StoriesTest'>;
}
declare module 'ignite-ir-boilerplate/commands/component.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/commands/component'>;
}
declare module 'ignite-ir-boilerplate/commands/container.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/commands/container'>;
}
declare module 'ignite-ir-boilerplate/commands/list.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/commands/list'>;
}
declare module 'ignite-ir-boilerplate/commands/listview.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/commands/listview'>;
}
declare module 'ignite-ir-boilerplate/commands/redux.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/commands/redux'>;
}
declare module 'ignite-ir-boilerplate/commands/saga.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/commands/saga'>;
}
declare module 'ignite-ir-boilerplate/commands/screen.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/commands/screen'>;
}
declare module 'ignite-ir-boilerplate/lib/patterns.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/lib/patterns'>;
}
declare module 'ignite-ir-boilerplate/lib/react-native-version.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/lib/react-native-version'>;
}
declare module 'ignite-ir-boilerplate/options.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/options'>;
}
declare module 'ignite-ir-boilerplate/plugin.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/plugin'>;
}
declare module 'ignite-ir-boilerplate/screenExamples.js' {
  declare module.exports: $Exports<'ignite-ir-boilerplate/screenExamples'>;
}
