// flow-typed signature: 28b3ff24f85a39c29e2eac49a4d4abcc
// flow-typed version: <<STUB>>/ignite-i18n_v^1.1.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ignite-i18n'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ignite-i18n' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ignite-i18n/plugin' {
  declare module.exports: any;
}

declare module 'ignite-i18n/templates/I18n/I18n' {
  declare module.exports: any;
}

declare module 'ignite-i18n/templates/I18n/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ignite-i18n/plugin.js' {
  declare module.exports: $Exports<'ignite-i18n/plugin'>;
}
declare module 'ignite-i18n/templates/I18n/I18n.js' {
  declare module.exports: $Exports<'ignite-i18n/templates/I18n/I18n'>;
}
declare module 'ignite-i18n/templates/I18n/index.js' {
  declare module.exports: $Exports<'ignite-i18n/templates/I18n/index'>;
}
