// flow-typed signature: 720ef478bce0066e88db61400579895a
// flow-typed version: <<STUB>>/ignite-standard_v^1.0.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ignite-standard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ignite-standard' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ignite-standard/__tests__/add' {
  declare module.exports: any;
}

declare module 'ignite-standard/__tests__/interface' {
  declare module.exports: any;
}

declare module 'ignite-standard/__tests__/remove' {
  declare module.exports: any;
}

declare module 'ignite-standard/patches' {
  declare module.exports: any;
}

declare module 'ignite-standard/plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ignite-standard/__tests__/add.js' {
  declare module.exports: $Exports<'ignite-standard/__tests__/add'>;
}
declare module 'ignite-standard/__tests__/interface.js' {
  declare module.exports: $Exports<'ignite-standard/__tests__/interface'>;
}
declare module 'ignite-standard/__tests__/remove.js' {
  declare module.exports: $Exports<'ignite-standard/__tests__/remove'>;
}
declare module 'ignite-standard/patches.js' {
  declare module.exports: $Exports<'ignite-standard/patches'>;
}
declare module 'ignite-standard/plugin.js' {
  declare module.exports: $Exports<'ignite-standard/plugin'>;
}
