// flow-typed signature: 52980af5218710a3e89a7acb4c885edd
// flow-typed version: <<STUB>>/ignite-redux-persist_v^1.1.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ignite-redux-persist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ignite-redux-persist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ignite-redux-persist/plugin' {
  declare module.exports: any;
}

declare module 'ignite-redux-persist/templates/ImmutablePersistenceTransform' {
  declare module.exports: any;
}

declare module 'ignite-redux-persist/templates/ReduxPersist' {
  declare module.exports: any;
}

declare module 'ignite-redux-persist/templates/Rehydration' {
  declare module.exports: any;
}

declare module 'ignite-redux-persist/test/add' {
  declare module.exports: any;
}

declare module 'ignite-redux-persist/test/interface' {
  declare module.exports: any;
}

declare module 'ignite-redux-persist/test/remove' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ignite-redux-persist/plugin.js' {
  declare module.exports: $Exports<'ignite-redux-persist/plugin'>;
}
declare module 'ignite-redux-persist/templates/ImmutablePersistenceTransform.js' {
  declare module.exports: $Exports<'ignite-redux-persist/templates/ImmutablePersistenceTransform'>;
}
declare module 'ignite-redux-persist/templates/ReduxPersist.js' {
  declare module.exports: $Exports<'ignite-redux-persist/templates/ReduxPersist'>;
}
declare module 'ignite-redux-persist/templates/Rehydration.js' {
  declare module.exports: $Exports<'ignite-redux-persist/templates/Rehydration'>;
}
declare module 'ignite-redux-persist/test/add.js' {
  declare module.exports: $Exports<'ignite-redux-persist/test/add'>;
}
declare module 'ignite-redux-persist/test/interface.js' {
  declare module.exports: $Exports<'ignite-redux-persist/test/interface'>;
}
declare module 'ignite-redux-persist/test/remove.js' {
  declare module.exports: $Exports<'ignite-redux-persist/test/remove'>;
}
