// flow-typed signature: 4f62b96ca727f4cdc813fe37bd4c0159
// flow-typed version: <<STUB>>/material-elements_v^0.0.21/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-elements'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-elements' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-elements/src/ActionButton/ActionButton.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/ActionButton/ActionButton.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/ActionButton/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Avatar/Avatar.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/Avatar/Avatar.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/Avatar/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Badge/Badge.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/Badge/Badge.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/Badge/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/BottomNavigation/BottomNavigation.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/BottomNavigation/BottomNavigationAction.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/BottomNavigation/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/BottomSheet/BottomSheet.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/BottomSheet/BottomSheet' {
  declare module.exports: any;
}

declare module 'material-elements/src/BottomSheet/BSDivider.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/BottomSheet/BSDivider' {
  declare module.exports: any;
}

declare module 'material-elements/src/BottomSheet/BSGridItem.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/BottomSheet/BSGridItem' {
  declare module.exports: any;
}

declare module 'material-elements/src/BottomSheet/BSListItem.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/BottomSheet/BSListItem' {
  declare module.exports: any;
}

declare module 'material-elements/src/BottomSheet/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Button/__test__/Button.test' {
  declare module.exports: any;
}

declare module 'material-elements/src/Button/Button.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/Button/Button' {
  declare module.exports: any;
}

declare module 'material-elements/src/Button/Button.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/Button/examples/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Button/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Card/Card.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/Card/Card.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/Card/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Checkbox/Checkbox.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/Checkbox/Checkbox.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/Checkbox/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Container/__test__/Container.test' {
  declare module.exports: any;
}

declare module 'material-elements/src/Container/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Dialog/Actions.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/Dialog/Actions.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/Dialog/Content.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/Dialog/Content.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/Dialog/Dialog.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/Dialog/Dialog.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/Dialog/DialogDefaultActions.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/Dialog/DialogDefaultActions.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/Dialog/DialogStackedActions.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/Dialog/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Dialog/Title.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/Dialog/Title.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/Divider/Divider.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/Divider/Divider.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/Divider/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Drawer/Drawer.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/Drawer/Header.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/Drawer/HeaderAccount.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/Drawer/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Drawer/Section.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/Icon/Icon.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/Icon/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/IconToggle/IconToggle.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/IconToggle/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Indicator/ball-indicator/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Indicator/ball-indicator/styles' {
  declare module.exports: any;
}

declare module 'material-elements/src/Indicator/bar-indicator/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Indicator/bar-indicator/styles' {
  declare module.exports: any;
}

declare module 'material-elements/src/Indicator/dot-indicator/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Indicator/dot-indicator/styles' {
  declare module.exports: any;
}

declare module 'material-elements/src/Indicator/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Indicator/indicator/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Indicator/material-indicator/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Indicator/material-indicator/styles' {
  declare module.exports: any;
}

declare module 'material-elements/src/Indicator/pacman-indicator/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Indicator/pacman-indicator/styles' {
  declare module.exports: any;
}

declare module 'material-elements/src/Indicator/pulse-indicator/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Indicator/pulse-indicator/styles' {
  declare module.exports: any;
}

declare module 'material-elements/src/Indicator/skype-indicator/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Indicator/skype-indicator/styles' {
  declare module.exports: any;
}

declare module 'material-elements/src/Indicator/ui-activity-indicator/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Indicator/ui-activity-indicator/styles' {
  declare module.exports: any;
}

declare module 'material-elements/src/Indicator/wave-indicator/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Indicator/wave-indicator/styles' {
  declare module.exports: any;
}

declare module 'material-elements/src/ListItem/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/ListItem/ListItem.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/ListItem/ListItem.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/Menu/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Menu/Menu' {
  declare module.exports: any;
}

declare module 'material-elements/src/Menu/MenuDivider' {
  declare module.exports: any;
}

declare module 'material-elements/src/Menu/MenuItem' {
  declare module.exports: any;
}

declare module 'material-elements/src/METester/ActionButtonExample' {
  declare module.exports: any;
}

declare module 'material-elements/src/METester/AvatarExample' {
  declare module.exports: any;
}

declare module 'material-elements/src/METester/BadgeExmaple' {
  declare module.exports: any;
}

declare module 'material-elements/src/METester/BottomSheetExample' {
  declare module.exports: any;
}

declare module 'material-elements/src/METester/ButtonExample' {
  declare module.exports: any;
}

declare module 'material-elements/src/METester/CardExample' {
  declare module.exports: any;
}

declare module 'material-elements/src/METester/CenterContainer' {
  declare module.exports: any;
}

declare module 'material-elements/src/METester/CheckboxExample' {
  declare module.exports: any;
}

declare module 'material-elements/src/METester/DialogExample' {
  declare module.exports: any;
}

declare module 'material-elements/src/METester/DividerExample' {
  declare module.exports: any;
}

declare module 'material-elements/src/METester/IconExample' {
  declare module.exports: any;
}

declare module 'material-elements/src/METester/ListItemExample' {
  declare module.exports: any;
}

declare module 'material-elements/src/METester/MenuExample' {
  declare module.exports: any;
}

declare module 'material-elements/src/METester/PlaceHolderExample' {
  declare module.exports: any;
}

declare module 'material-elements/src/METester/RadioButtonExample' {
  declare module.exports: any;
}

declare module 'material-elements/src/METester/SimpleToolbarExample' {
  declare module.exports: any;
}

declare module 'material-elements/src/METester/ToastExample' {
  declare module.exports: any;
}

declare module 'material-elements/src/METester/ToolbarExample' {
  declare module.exports: any;
}

declare module 'material-elements/src/Modalbox/ModalBox' {
  declare module.exports: any;
}

declare module 'material-elements/src/Placeholder/Box' {
  declare module.exports: any;
}

declare module 'material-elements/src/Placeholder/ImageContent' {
  declare module.exports: any;
}

declare module 'material-elements/src/Placeholder/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Placeholder/Line' {
  declare module.exports: any;
}

declare module 'material-elements/src/Placeholder/Media' {
  declare module.exports: any;
}

declare module 'material-elements/src/Placeholder/MultiWords' {
  declare module.exports: any;
}

declare module 'material-elements/src/Placeholder/Paragraph' {
  declare module.exports: any;
}

declare module 'material-elements/src/PressRipple/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/PressRipple/PressRipple' {
  declare module.exports: any;
}

declare module 'material-elements/src/RadioButton/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/RadioButton/RadioButton.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/RadioButton/RadioButton.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/Ripple/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Ripple/styles' {
  declare module.exports: any;
}

declare module 'material-elements/src/Ripple/Test/app' {
  declare module.exports: any;
}

declare module 'material-elements/src/RippleFeedback/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/RippleFeedback/RippleFeedback.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/RippleFeedback/RippleFeedback.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/SimpleToolbar/CenterElement.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/SimpleToolbar/CenterElement.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/SimpleToolbar/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/SimpleToolbar/SimpleToolbar.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/SimpleToolbar/SimpleToolbar.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/Snackbar/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Snackbar/Snackbar.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/styles/__test__/getPlatformElevation.test' {
  declare module.exports: any;
}

declare module 'material-elements/src/styles/__test__/getTheme.test' {
  declare module.exports: any;
}

declare module 'material-elements/src/styles/colors' {
  declare module.exports: any;
}

declare module 'material-elements/src/styles/constants' {
  declare module.exports: any;
}

declare module 'material-elements/src/styles/getPlatformElevation.android' {
  declare module.exports: any;
}

declare module 'material-elements/src/styles/getPlatformElevation.ios' {
  declare module.exports: any;
}

declare module 'material-elements/src/styles/getPlatformElevation.web' {
  declare module.exports: any;
}

declare module 'material-elements/src/styles/getTheme' {
  declare module.exports: any;
}

declare module 'material-elements/src/styles/Metrics' {
  declare module.exports: any;
}

declare module 'material-elements/src/styles/spacing' {
  declare module.exports: any;
}

declare module 'material-elements/src/styles/ThemeProvider.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/styles/themes/light' {
  declare module.exports: any;
}

declare module 'material-elements/src/styles/typography' {
  declare module.exports: any;
}

declare module 'material-elements/src/Subheader/__test__/Subheader.test' {
  declare module.exports: any;
}

declare module 'material-elements/src/Subheader/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Subheader/Subheader.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/Subheader/Subheader.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/TextField/FloatingLabel' {
  declare module.exports: any;
}

declare module 'material-elements/src/TextField/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/TextField/TextField' {
  declare module.exports: any;
}

declare module 'material-elements/src/TextField/TextFieldBase' {
  declare module.exports: any;
}

declare module 'material-elements/src/TextField/Underline' {
  declare module.exports: any;
}

declare module 'material-elements/src/Toast/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Toast/Toast.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/Toast/Toast' {
  declare module.exports: any;
}

declare module 'material-elements/src/Toolbar/__test__/Toolbar.test' {
  declare module.exports: any;
}

declare module 'material-elements/src/Toolbar/CenterElement.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/Toolbar/CenterElement.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/Toolbar/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/Toolbar/LeftElement.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/Toolbar/LeftElement.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/Toolbar/RightElement.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/Toolbar/RightElement.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/Toolbar/Toolbar.flow' {
  declare module.exports: any;
}

declare module 'material-elements/src/Toolbar/Toolbar.react' {
  declare module.exports: any;
}

declare module 'material-elements/src/TypeDifinition/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/utils/__test__/isFunction.test' {
  declare module.exports: any;
}

declare module 'material-elements/src/utils/index' {
  declare module.exports: any;
}

declare module 'material-elements/src/utils/isFunction' {
  declare module.exports: any;
}

declare module 'material-elements/src/utils/MotionCurve' {
  declare module.exports: any;
}

declare module 'material-elements/src/utils/MotionDuration' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-elements/src/ActionButton/ActionButton.flow.js' {
  declare module.exports: $Exports<'material-elements/src/ActionButton/ActionButton.flow'>;
}
declare module 'material-elements/src/ActionButton/ActionButton.react.js' {
  declare module.exports: $Exports<'material-elements/src/ActionButton/ActionButton.react'>;
}
declare module 'material-elements/src/ActionButton/index.js' {
  declare module.exports: $Exports<'material-elements/src/ActionButton/index'>;
}
declare module 'material-elements/src/Avatar/Avatar.flow.js' {
  declare module.exports: $Exports<'material-elements/src/Avatar/Avatar.flow'>;
}
declare module 'material-elements/src/Avatar/Avatar.react.js' {
  declare module.exports: $Exports<'material-elements/src/Avatar/Avatar.react'>;
}
declare module 'material-elements/src/Avatar/index.js' {
  declare module.exports: $Exports<'material-elements/src/Avatar/index'>;
}
declare module 'material-elements/src/Badge/Badge.flow.js' {
  declare module.exports: $Exports<'material-elements/src/Badge/Badge.flow'>;
}
declare module 'material-elements/src/Badge/Badge.react.js' {
  declare module.exports: $Exports<'material-elements/src/Badge/Badge.react'>;
}
declare module 'material-elements/src/Badge/index.js' {
  declare module.exports: $Exports<'material-elements/src/Badge/index'>;
}
declare module 'material-elements/src/BottomNavigation/BottomNavigation.react.js' {
  declare module.exports: $Exports<'material-elements/src/BottomNavigation/BottomNavigation.react'>;
}
declare module 'material-elements/src/BottomNavigation/BottomNavigationAction.react.js' {
  declare module.exports: $Exports<'material-elements/src/BottomNavigation/BottomNavigationAction.react'>;
}
declare module 'material-elements/src/BottomNavigation/index.js' {
  declare module.exports: $Exports<'material-elements/src/BottomNavigation/index'>;
}
declare module 'material-elements/src/BottomSheet/BottomSheet.flow.js' {
  declare module.exports: $Exports<'material-elements/src/BottomSheet/BottomSheet.flow'>;
}
declare module 'material-elements/src/BottomSheet/BottomSheet.js' {
  declare module.exports: $Exports<'material-elements/src/BottomSheet/BottomSheet'>;
}
declare module 'material-elements/src/BottomSheet/BSDivider.flow.js' {
  declare module.exports: $Exports<'material-elements/src/BottomSheet/BSDivider.flow'>;
}
declare module 'material-elements/src/BottomSheet/BSDivider.js' {
  declare module.exports: $Exports<'material-elements/src/BottomSheet/BSDivider'>;
}
declare module 'material-elements/src/BottomSheet/BSGridItem.flow.js' {
  declare module.exports: $Exports<'material-elements/src/BottomSheet/BSGridItem.flow'>;
}
declare module 'material-elements/src/BottomSheet/BSGridItem.js' {
  declare module.exports: $Exports<'material-elements/src/BottomSheet/BSGridItem'>;
}
declare module 'material-elements/src/BottomSheet/BSListItem.flow.js' {
  declare module.exports: $Exports<'material-elements/src/BottomSheet/BSListItem.flow'>;
}
declare module 'material-elements/src/BottomSheet/BSListItem.js' {
  declare module.exports: $Exports<'material-elements/src/BottomSheet/BSListItem'>;
}
declare module 'material-elements/src/BottomSheet/index.js' {
  declare module.exports: $Exports<'material-elements/src/BottomSheet/index'>;
}
declare module 'material-elements/src/Button/__test__/Button.test.js' {
  declare module.exports: $Exports<'material-elements/src/Button/__test__/Button.test'>;
}
declare module 'material-elements/src/Button/Button.flow.js' {
  declare module.exports: $Exports<'material-elements/src/Button/Button.flow'>;
}
declare module 'material-elements/src/Button/Button.js' {
  declare module.exports: $Exports<'material-elements/src/Button/Button'>;
}
declare module 'material-elements/src/Button/Button.react.js' {
  declare module.exports: $Exports<'material-elements/src/Button/Button.react'>;
}
declare module 'material-elements/src/Button/examples/index.js' {
  declare module.exports: $Exports<'material-elements/src/Button/examples/index'>;
}
declare module 'material-elements/src/Button/index.js' {
  declare module.exports: $Exports<'material-elements/src/Button/index'>;
}
declare module 'material-elements/src/Card/Card.flow.js' {
  declare module.exports: $Exports<'material-elements/src/Card/Card.flow'>;
}
declare module 'material-elements/src/Card/Card.react.js' {
  declare module.exports: $Exports<'material-elements/src/Card/Card.react'>;
}
declare module 'material-elements/src/Card/index.js' {
  declare module.exports: $Exports<'material-elements/src/Card/index'>;
}
declare module 'material-elements/src/Checkbox/Checkbox.flow.js' {
  declare module.exports: $Exports<'material-elements/src/Checkbox/Checkbox.flow'>;
}
declare module 'material-elements/src/Checkbox/Checkbox.react.js' {
  declare module.exports: $Exports<'material-elements/src/Checkbox/Checkbox.react'>;
}
declare module 'material-elements/src/Checkbox/index.js' {
  declare module.exports: $Exports<'material-elements/src/Checkbox/index'>;
}
declare module 'material-elements/src/Container/__test__/Container.test.js' {
  declare module.exports: $Exports<'material-elements/src/Container/__test__/Container.test'>;
}
declare module 'material-elements/src/Container/index.js' {
  declare module.exports: $Exports<'material-elements/src/Container/index'>;
}
declare module 'material-elements/src/Dialog/Actions.flow.js' {
  declare module.exports: $Exports<'material-elements/src/Dialog/Actions.flow'>;
}
declare module 'material-elements/src/Dialog/Actions.react.js' {
  declare module.exports: $Exports<'material-elements/src/Dialog/Actions.react'>;
}
declare module 'material-elements/src/Dialog/Content.flow.js' {
  declare module.exports: $Exports<'material-elements/src/Dialog/Content.flow'>;
}
declare module 'material-elements/src/Dialog/Content.react.js' {
  declare module.exports: $Exports<'material-elements/src/Dialog/Content.react'>;
}
declare module 'material-elements/src/Dialog/Dialog.flow.js' {
  declare module.exports: $Exports<'material-elements/src/Dialog/Dialog.flow'>;
}
declare module 'material-elements/src/Dialog/Dialog.react.js' {
  declare module.exports: $Exports<'material-elements/src/Dialog/Dialog.react'>;
}
declare module 'material-elements/src/Dialog/DialogDefaultActions.flow.js' {
  declare module.exports: $Exports<'material-elements/src/Dialog/DialogDefaultActions.flow'>;
}
declare module 'material-elements/src/Dialog/DialogDefaultActions.react.js' {
  declare module.exports: $Exports<'material-elements/src/Dialog/DialogDefaultActions.react'>;
}
declare module 'material-elements/src/Dialog/DialogStackedActions.react.js' {
  declare module.exports: $Exports<'material-elements/src/Dialog/DialogStackedActions.react'>;
}
declare module 'material-elements/src/Dialog/index.js' {
  declare module.exports: $Exports<'material-elements/src/Dialog/index'>;
}
declare module 'material-elements/src/Dialog/Title.flow.js' {
  declare module.exports: $Exports<'material-elements/src/Dialog/Title.flow'>;
}
declare module 'material-elements/src/Dialog/Title.react.js' {
  declare module.exports: $Exports<'material-elements/src/Dialog/Title.react'>;
}
declare module 'material-elements/src/Divider/Divider.flow.js' {
  declare module.exports: $Exports<'material-elements/src/Divider/Divider.flow'>;
}
declare module 'material-elements/src/Divider/Divider.react.js' {
  declare module.exports: $Exports<'material-elements/src/Divider/Divider.react'>;
}
declare module 'material-elements/src/Divider/index.js' {
  declare module.exports: $Exports<'material-elements/src/Divider/index'>;
}
declare module 'material-elements/src/Drawer/Drawer.react.js' {
  declare module.exports: $Exports<'material-elements/src/Drawer/Drawer.react'>;
}
declare module 'material-elements/src/Drawer/Header.react.js' {
  declare module.exports: $Exports<'material-elements/src/Drawer/Header.react'>;
}
declare module 'material-elements/src/Drawer/HeaderAccount.react.js' {
  declare module.exports: $Exports<'material-elements/src/Drawer/HeaderAccount.react'>;
}
declare module 'material-elements/src/Drawer/index.js' {
  declare module.exports: $Exports<'material-elements/src/Drawer/index'>;
}
declare module 'material-elements/src/Drawer/Section.react.js' {
  declare module.exports: $Exports<'material-elements/src/Drawer/Section.react'>;
}
declare module 'material-elements/src/Icon/Icon.flow.js' {
  declare module.exports: $Exports<'material-elements/src/Icon/Icon.flow'>;
}
declare module 'material-elements/src/Icon/index.js' {
  declare module.exports: $Exports<'material-elements/src/Icon/index'>;
}
declare module 'material-elements/src/IconToggle/IconToggle.react.js' {
  declare module.exports: $Exports<'material-elements/src/IconToggle/IconToggle.react'>;
}
declare module 'material-elements/src/IconToggle/index.js' {
  declare module.exports: $Exports<'material-elements/src/IconToggle/index'>;
}
declare module 'material-elements/src/index.js' {
  declare module.exports: $Exports<'material-elements/src/index'>;
}
declare module 'material-elements/src/Indicator/ball-indicator/index.js' {
  declare module.exports: $Exports<'material-elements/src/Indicator/ball-indicator/index'>;
}
declare module 'material-elements/src/Indicator/ball-indicator/styles.js' {
  declare module.exports: $Exports<'material-elements/src/Indicator/ball-indicator/styles'>;
}
declare module 'material-elements/src/Indicator/bar-indicator/index.js' {
  declare module.exports: $Exports<'material-elements/src/Indicator/bar-indicator/index'>;
}
declare module 'material-elements/src/Indicator/bar-indicator/styles.js' {
  declare module.exports: $Exports<'material-elements/src/Indicator/bar-indicator/styles'>;
}
declare module 'material-elements/src/Indicator/dot-indicator/index.js' {
  declare module.exports: $Exports<'material-elements/src/Indicator/dot-indicator/index'>;
}
declare module 'material-elements/src/Indicator/dot-indicator/styles.js' {
  declare module.exports: $Exports<'material-elements/src/Indicator/dot-indicator/styles'>;
}
declare module 'material-elements/src/Indicator/index.js' {
  declare module.exports: $Exports<'material-elements/src/Indicator/index'>;
}
declare module 'material-elements/src/Indicator/indicator/index.js' {
  declare module.exports: $Exports<'material-elements/src/Indicator/indicator/index'>;
}
declare module 'material-elements/src/Indicator/material-indicator/index.js' {
  declare module.exports: $Exports<'material-elements/src/Indicator/material-indicator/index'>;
}
declare module 'material-elements/src/Indicator/material-indicator/styles.js' {
  declare module.exports: $Exports<'material-elements/src/Indicator/material-indicator/styles'>;
}
declare module 'material-elements/src/Indicator/pacman-indicator/index.js' {
  declare module.exports: $Exports<'material-elements/src/Indicator/pacman-indicator/index'>;
}
declare module 'material-elements/src/Indicator/pacman-indicator/styles.js' {
  declare module.exports: $Exports<'material-elements/src/Indicator/pacman-indicator/styles'>;
}
declare module 'material-elements/src/Indicator/pulse-indicator/index.js' {
  declare module.exports: $Exports<'material-elements/src/Indicator/pulse-indicator/index'>;
}
declare module 'material-elements/src/Indicator/pulse-indicator/styles.js' {
  declare module.exports: $Exports<'material-elements/src/Indicator/pulse-indicator/styles'>;
}
declare module 'material-elements/src/Indicator/skype-indicator/index.js' {
  declare module.exports: $Exports<'material-elements/src/Indicator/skype-indicator/index'>;
}
declare module 'material-elements/src/Indicator/skype-indicator/styles.js' {
  declare module.exports: $Exports<'material-elements/src/Indicator/skype-indicator/styles'>;
}
declare module 'material-elements/src/Indicator/ui-activity-indicator/index.js' {
  declare module.exports: $Exports<'material-elements/src/Indicator/ui-activity-indicator/index'>;
}
declare module 'material-elements/src/Indicator/ui-activity-indicator/styles.js' {
  declare module.exports: $Exports<'material-elements/src/Indicator/ui-activity-indicator/styles'>;
}
declare module 'material-elements/src/Indicator/wave-indicator/index.js' {
  declare module.exports: $Exports<'material-elements/src/Indicator/wave-indicator/index'>;
}
declare module 'material-elements/src/Indicator/wave-indicator/styles.js' {
  declare module.exports: $Exports<'material-elements/src/Indicator/wave-indicator/styles'>;
}
declare module 'material-elements/src/ListItem/index.js' {
  declare module.exports: $Exports<'material-elements/src/ListItem/index'>;
}
declare module 'material-elements/src/ListItem/ListItem.flow.js' {
  declare module.exports: $Exports<'material-elements/src/ListItem/ListItem.flow'>;
}
declare module 'material-elements/src/ListItem/ListItem.react.js' {
  declare module.exports: $Exports<'material-elements/src/ListItem/ListItem.react'>;
}
declare module 'material-elements/src/Menu/index.js' {
  declare module.exports: $Exports<'material-elements/src/Menu/index'>;
}
declare module 'material-elements/src/Menu/Menu.js' {
  declare module.exports: $Exports<'material-elements/src/Menu/Menu'>;
}
declare module 'material-elements/src/Menu/MenuDivider.js' {
  declare module.exports: $Exports<'material-elements/src/Menu/MenuDivider'>;
}
declare module 'material-elements/src/Menu/MenuItem.js' {
  declare module.exports: $Exports<'material-elements/src/Menu/MenuItem'>;
}
declare module 'material-elements/src/METester/ActionButtonExample.js' {
  declare module.exports: $Exports<'material-elements/src/METester/ActionButtonExample'>;
}
declare module 'material-elements/src/METester/AvatarExample.js' {
  declare module.exports: $Exports<'material-elements/src/METester/AvatarExample'>;
}
declare module 'material-elements/src/METester/BadgeExmaple.js' {
  declare module.exports: $Exports<'material-elements/src/METester/BadgeExmaple'>;
}
declare module 'material-elements/src/METester/BottomSheetExample.js' {
  declare module.exports: $Exports<'material-elements/src/METester/BottomSheetExample'>;
}
declare module 'material-elements/src/METester/ButtonExample.js' {
  declare module.exports: $Exports<'material-elements/src/METester/ButtonExample'>;
}
declare module 'material-elements/src/METester/CardExample.js' {
  declare module.exports: $Exports<'material-elements/src/METester/CardExample'>;
}
declare module 'material-elements/src/METester/CenterContainer.js' {
  declare module.exports: $Exports<'material-elements/src/METester/CenterContainer'>;
}
declare module 'material-elements/src/METester/CheckboxExample.js' {
  declare module.exports: $Exports<'material-elements/src/METester/CheckboxExample'>;
}
declare module 'material-elements/src/METester/DialogExample.js' {
  declare module.exports: $Exports<'material-elements/src/METester/DialogExample'>;
}
declare module 'material-elements/src/METester/DividerExample.js' {
  declare module.exports: $Exports<'material-elements/src/METester/DividerExample'>;
}
declare module 'material-elements/src/METester/IconExample.js' {
  declare module.exports: $Exports<'material-elements/src/METester/IconExample'>;
}
declare module 'material-elements/src/METester/ListItemExample.js' {
  declare module.exports: $Exports<'material-elements/src/METester/ListItemExample'>;
}
declare module 'material-elements/src/METester/MenuExample.js' {
  declare module.exports: $Exports<'material-elements/src/METester/MenuExample'>;
}
declare module 'material-elements/src/METester/PlaceHolderExample.js' {
  declare module.exports: $Exports<'material-elements/src/METester/PlaceHolderExample'>;
}
declare module 'material-elements/src/METester/RadioButtonExample.js' {
  declare module.exports: $Exports<'material-elements/src/METester/RadioButtonExample'>;
}
declare module 'material-elements/src/METester/SimpleToolbarExample.js' {
  declare module.exports: $Exports<'material-elements/src/METester/SimpleToolbarExample'>;
}
declare module 'material-elements/src/METester/ToastExample.js' {
  declare module.exports: $Exports<'material-elements/src/METester/ToastExample'>;
}
declare module 'material-elements/src/METester/ToolbarExample.js' {
  declare module.exports: $Exports<'material-elements/src/METester/ToolbarExample'>;
}
declare module 'material-elements/src/Modalbox/ModalBox.js' {
  declare module.exports: $Exports<'material-elements/src/Modalbox/ModalBox'>;
}
declare module 'material-elements/src/Placeholder/Box.js' {
  declare module.exports: $Exports<'material-elements/src/Placeholder/Box'>;
}
declare module 'material-elements/src/Placeholder/ImageContent.js' {
  declare module.exports: $Exports<'material-elements/src/Placeholder/ImageContent'>;
}
declare module 'material-elements/src/Placeholder/index.js' {
  declare module.exports: $Exports<'material-elements/src/Placeholder/index'>;
}
declare module 'material-elements/src/Placeholder/Line.js' {
  declare module.exports: $Exports<'material-elements/src/Placeholder/Line'>;
}
declare module 'material-elements/src/Placeholder/Media.js' {
  declare module.exports: $Exports<'material-elements/src/Placeholder/Media'>;
}
declare module 'material-elements/src/Placeholder/MultiWords.js' {
  declare module.exports: $Exports<'material-elements/src/Placeholder/MultiWords'>;
}
declare module 'material-elements/src/Placeholder/Paragraph.js' {
  declare module.exports: $Exports<'material-elements/src/Placeholder/Paragraph'>;
}
declare module 'material-elements/src/PressRipple/index.js' {
  declare module.exports: $Exports<'material-elements/src/PressRipple/index'>;
}
declare module 'material-elements/src/PressRipple/PressRipple.js' {
  declare module.exports: $Exports<'material-elements/src/PressRipple/PressRipple'>;
}
declare module 'material-elements/src/RadioButton/index.js' {
  declare module.exports: $Exports<'material-elements/src/RadioButton/index'>;
}
declare module 'material-elements/src/RadioButton/RadioButton.flow.js' {
  declare module.exports: $Exports<'material-elements/src/RadioButton/RadioButton.flow'>;
}
declare module 'material-elements/src/RadioButton/RadioButton.react.js' {
  declare module.exports: $Exports<'material-elements/src/RadioButton/RadioButton.react'>;
}
declare module 'material-elements/src/Ripple/index.js' {
  declare module.exports: $Exports<'material-elements/src/Ripple/index'>;
}
declare module 'material-elements/src/Ripple/styles.js' {
  declare module.exports: $Exports<'material-elements/src/Ripple/styles'>;
}
declare module 'material-elements/src/Ripple/Test/app.js' {
  declare module.exports: $Exports<'material-elements/src/Ripple/Test/app'>;
}
declare module 'material-elements/src/RippleFeedback/index.js' {
  declare module.exports: $Exports<'material-elements/src/RippleFeedback/index'>;
}
declare module 'material-elements/src/RippleFeedback/RippleFeedback.flow.js' {
  declare module.exports: $Exports<'material-elements/src/RippleFeedback/RippleFeedback.flow'>;
}
declare module 'material-elements/src/RippleFeedback/RippleFeedback.react.js' {
  declare module.exports: $Exports<'material-elements/src/RippleFeedback/RippleFeedback.react'>;
}
declare module 'material-elements/src/SimpleToolbar/CenterElement.flow.js' {
  declare module.exports: $Exports<'material-elements/src/SimpleToolbar/CenterElement.flow'>;
}
declare module 'material-elements/src/SimpleToolbar/CenterElement.react.js' {
  declare module.exports: $Exports<'material-elements/src/SimpleToolbar/CenterElement.react'>;
}
declare module 'material-elements/src/SimpleToolbar/index.js' {
  declare module.exports: $Exports<'material-elements/src/SimpleToolbar/index'>;
}
declare module 'material-elements/src/SimpleToolbar/SimpleToolbar.flow.js' {
  declare module.exports: $Exports<'material-elements/src/SimpleToolbar/SimpleToolbar.flow'>;
}
declare module 'material-elements/src/SimpleToolbar/SimpleToolbar.react.js' {
  declare module.exports: $Exports<'material-elements/src/SimpleToolbar/SimpleToolbar.react'>;
}
declare module 'material-elements/src/Snackbar/index.js' {
  declare module.exports: $Exports<'material-elements/src/Snackbar/index'>;
}
declare module 'material-elements/src/Snackbar/Snackbar.react.js' {
  declare module.exports: $Exports<'material-elements/src/Snackbar/Snackbar.react'>;
}
declare module 'material-elements/src/styles/__test__/getPlatformElevation.test.js' {
  declare module.exports: $Exports<'material-elements/src/styles/__test__/getPlatformElevation.test'>;
}
declare module 'material-elements/src/styles/__test__/getTheme.test.js' {
  declare module.exports: $Exports<'material-elements/src/styles/__test__/getTheme.test'>;
}
declare module 'material-elements/src/styles/colors.js' {
  declare module.exports: $Exports<'material-elements/src/styles/colors'>;
}
declare module 'material-elements/src/styles/constants.js' {
  declare module.exports: $Exports<'material-elements/src/styles/constants'>;
}
declare module 'material-elements/src/styles/getPlatformElevation.android.js' {
  declare module.exports: $Exports<'material-elements/src/styles/getPlatformElevation.android'>;
}
declare module 'material-elements/src/styles/getPlatformElevation.ios.js' {
  declare module.exports: $Exports<'material-elements/src/styles/getPlatformElevation.ios'>;
}
declare module 'material-elements/src/styles/getPlatformElevation.web.js' {
  declare module.exports: $Exports<'material-elements/src/styles/getPlatformElevation.web'>;
}
declare module 'material-elements/src/styles/getTheme.js' {
  declare module.exports: $Exports<'material-elements/src/styles/getTheme'>;
}
declare module 'material-elements/src/styles/Metrics.js' {
  declare module.exports: $Exports<'material-elements/src/styles/Metrics'>;
}
declare module 'material-elements/src/styles/spacing.js' {
  declare module.exports: $Exports<'material-elements/src/styles/spacing'>;
}
declare module 'material-elements/src/styles/ThemeProvider.react.js' {
  declare module.exports: $Exports<'material-elements/src/styles/ThemeProvider.react'>;
}
declare module 'material-elements/src/styles/themes/light.js' {
  declare module.exports: $Exports<'material-elements/src/styles/themes/light'>;
}
declare module 'material-elements/src/styles/typography.js' {
  declare module.exports: $Exports<'material-elements/src/styles/typography'>;
}
declare module 'material-elements/src/Subheader/__test__/Subheader.test.js' {
  declare module.exports: $Exports<'material-elements/src/Subheader/__test__/Subheader.test'>;
}
declare module 'material-elements/src/Subheader/index.js' {
  declare module.exports: $Exports<'material-elements/src/Subheader/index'>;
}
declare module 'material-elements/src/Subheader/Subheader.flow.js' {
  declare module.exports: $Exports<'material-elements/src/Subheader/Subheader.flow'>;
}
declare module 'material-elements/src/Subheader/Subheader.react.js' {
  declare module.exports: $Exports<'material-elements/src/Subheader/Subheader.react'>;
}
declare module 'material-elements/src/TextField/FloatingLabel.js' {
  declare module.exports: $Exports<'material-elements/src/TextField/FloatingLabel'>;
}
declare module 'material-elements/src/TextField/index.js' {
  declare module.exports: $Exports<'material-elements/src/TextField/index'>;
}
declare module 'material-elements/src/TextField/TextField.js' {
  declare module.exports: $Exports<'material-elements/src/TextField/TextField'>;
}
declare module 'material-elements/src/TextField/TextFieldBase.js' {
  declare module.exports: $Exports<'material-elements/src/TextField/TextFieldBase'>;
}
declare module 'material-elements/src/TextField/Underline.js' {
  declare module.exports: $Exports<'material-elements/src/TextField/Underline'>;
}
declare module 'material-elements/src/Toast/index.js' {
  declare module.exports: $Exports<'material-elements/src/Toast/index'>;
}
declare module 'material-elements/src/Toast/Toast.flow.js' {
  declare module.exports: $Exports<'material-elements/src/Toast/Toast.flow'>;
}
declare module 'material-elements/src/Toast/Toast.js' {
  declare module.exports: $Exports<'material-elements/src/Toast/Toast'>;
}
declare module 'material-elements/src/Toolbar/__test__/Toolbar.test.js' {
  declare module.exports: $Exports<'material-elements/src/Toolbar/__test__/Toolbar.test'>;
}
declare module 'material-elements/src/Toolbar/CenterElement.flow.js' {
  declare module.exports: $Exports<'material-elements/src/Toolbar/CenterElement.flow'>;
}
declare module 'material-elements/src/Toolbar/CenterElement.react.js' {
  declare module.exports: $Exports<'material-elements/src/Toolbar/CenterElement.react'>;
}
declare module 'material-elements/src/Toolbar/index.js' {
  declare module.exports: $Exports<'material-elements/src/Toolbar/index'>;
}
declare module 'material-elements/src/Toolbar/LeftElement.flow.js' {
  declare module.exports: $Exports<'material-elements/src/Toolbar/LeftElement.flow'>;
}
declare module 'material-elements/src/Toolbar/LeftElement.react.js' {
  declare module.exports: $Exports<'material-elements/src/Toolbar/LeftElement.react'>;
}
declare module 'material-elements/src/Toolbar/RightElement.flow.js' {
  declare module.exports: $Exports<'material-elements/src/Toolbar/RightElement.flow'>;
}
declare module 'material-elements/src/Toolbar/RightElement.react.js' {
  declare module.exports: $Exports<'material-elements/src/Toolbar/RightElement.react'>;
}
declare module 'material-elements/src/Toolbar/Toolbar.flow.js' {
  declare module.exports: $Exports<'material-elements/src/Toolbar/Toolbar.flow'>;
}
declare module 'material-elements/src/Toolbar/Toolbar.react.js' {
  declare module.exports: $Exports<'material-elements/src/Toolbar/Toolbar.react'>;
}
declare module 'material-elements/src/TypeDifinition/index.js' {
  declare module.exports: $Exports<'material-elements/src/TypeDifinition/index'>;
}
declare module 'material-elements/src/utils/__test__/isFunction.test.js' {
  declare module.exports: $Exports<'material-elements/src/utils/__test__/isFunction.test'>;
}
declare module 'material-elements/src/utils/index.js' {
  declare module.exports: $Exports<'material-elements/src/utils/index'>;
}
declare module 'material-elements/src/utils/isFunction.js' {
  declare module.exports: $Exports<'material-elements/src/utils/isFunction'>;
}
declare module 'material-elements/src/utils/MotionCurve.js' {
  declare module.exports: $Exports<'material-elements/src/utils/MotionCurve'>;
}
declare module 'material-elements/src/utils/MotionDuration.js' {
  declare module.exports: $Exports<'material-elements/src/utils/MotionDuration'>;
}
