// flow-typed signature: 23f7dbafc738c40adf0c29111b7f0f53
// flow-typed version: <<STUB>>/reactotron-redux-saga_v^1.13.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reactotron-redux-saga'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reactotron-redux-saga' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reactotron-redux-saga/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reactotron-redux-saga/dist/index.js' {
  declare module.exports: $Exports<'reactotron-redux-saga/dist/index'>;
}
