// flow-typed signature: 084f5609cb46ee9ae2d5d8fd128ee970
// flow-typed version: <<STUB>>/reduxsauce_v0.7.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reduxsauce'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reduxsauce' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reduxsauce/dist/reduxsauce' {
  declare module.exports: any;
}

declare module 'reduxsauce/lib/createActions' {
  declare module.exports: any;
}

declare module 'reduxsauce/lib/createReducer' {
  declare module.exports: any;
}

declare module 'reduxsauce/lib/createTypes' {
  declare module.exports: any;
}

declare module 'reduxsauce/lib/reduxsauce' {
  declare module.exports: any;
}

declare module 'reduxsauce/lib/resettableReducer' {
  declare module.exports: any;
}

declare module 'reduxsauce/lib/Types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reduxsauce/dist/reduxsauce.js' {
  declare module.exports: $Exports<'reduxsauce/dist/reduxsauce'>;
}
declare module 'reduxsauce/lib/createActions.js' {
  declare module.exports: $Exports<'reduxsauce/lib/createActions'>;
}
declare module 'reduxsauce/lib/createReducer.js' {
  declare module.exports: $Exports<'reduxsauce/lib/createReducer'>;
}
declare module 'reduxsauce/lib/createTypes.js' {
  declare module.exports: $Exports<'reduxsauce/lib/createTypes'>;
}
declare module 'reduxsauce/lib/reduxsauce.js' {
  declare module.exports: $Exports<'reduxsauce/lib/reduxsauce'>;
}
declare module 'reduxsauce/lib/resettableReducer.js' {
  declare module.exports: $Exports<'reduxsauce/lib/resettableReducer'>;
}
declare module 'reduxsauce/lib/Types.js' {
  declare module.exports: $Exports<'reduxsauce/lib/Types'>;
}
